window.CERTIFICATE_ITEMS = [
    {
        "id":  "cert-001",
        "sort":  1,
        "image":  "./items/item-001.jpg",
        "originalFile":  "【Google】【證照】Google Gemini Certified Educator (YU-TING SHIH).jpg",
        "titleZh":  "Google Gemini Certified Educator (YU-TING SHIH)",
        "titleEn":  "Google Gemini Certified Educator (YU-TING SHIH)",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-002",
        "sort":  2,
        "image":  "./items/item-002.png",
        "originalFile":  "【Google】【證照】Google 認證 GFE Trainer Skills Assessment - Traditional Chinese_1.png",
        "titleZh":  "Google 認證 GFE Trainer Skills Assessment - Traditional Chinese",
        "titleEn":  "Google 認證 GFE Trainer Skills Assessment - Traditional Chinese",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-003",
        "sort":  3,
        "image":  "./items/item-003.png",
        "originalFile":  "【Google】Accelerate Your Job Search with AI.png",
        "titleZh":  "Accelerate Your Job Search with AI",
        "titleEn":  "Accelerate Your Job Search with AI",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-004",
        "sort":  4,
        "image":  "./items/item-004.png",
        "originalFile":  "【Google】Assets, Threats, and Vulnerabilities.png",
        "titleZh":  "Assets, Threats, and Vulnerabilities",
        "titleEn":  "Assets, Threats, and Vulnerabilities",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-005",
        "sort":  5,
        "image":  "./items/item-005.png",
        "originalFile":  "【Google】Automate Cybersecurity Tasks with Python.png",
        "titleZh":  "Automate Cybersecurity Tasks with Python",
        "titleEn":  "Automate Cybersecurity Tasks with Python",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-006",
        "sort":  6,
        "image":  "./items/item-006.png",
        "originalFile":  "【Google】Cloud Technical Series  AI in Action.png",
        "titleZh":  "Cloud Technical Series AI in Action",
        "titleEn":  "Cloud Technical Series AI in Action",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-007",
        "sort":  7,
        "image":  "./items/item-007.png",
        "originalFile":  "【Google】Connect and Protect Networks and Network Security.png",
        "titleZh":  "Connect and Protect Networks and Network Security",
        "titleEn":  "Connect and Protect Networks and Network Security",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-008",
        "sort":  8,
        "image":  "./items/item-008.png",
        "originalFile":  "【Google】Foundations of Cybersecurity.png",
        "titleZh":  "Foundations of Cybersecurity",
        "titleEn":  "Foundations of Cybersecurity",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-009",
        "sort":  9,
        "image":  "./items/item-009.png",
        "originalFile":  "【Google】Generative AI Leader _ Google Cloud Skills Boost_1.png",
        "titleZh":  "Generative AI Leader _ Google Cloud Skills Boost",
        "titleEn":  "Generative AI Leader _ Google Cloud Skills Boost",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-010",
        "sort":  10,
        "image":  "./items/item-010.png",
        "originalFile":  "【Google】Google Cybersecurity.png",
        "titleZh":  "Google Cybersecurity",
        "titleEn":  "Google Cybersecurity",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-011",
        "sort":  11,
        "image":  "./items/item-011.png",
        "originalFile":  "【Google】Google 認證.png",
        "titleZh":  "Google 認證",
        "titleEn":  "Google 認證",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-012",
        "sort":  12,
        "image":  "./items/item-012.png",
        "originalFile":  "【Google】Play It Safe- Manage Security Risks.png",
        "titleZh":  "Play It Safe- Manage Security Risks",
        "titleEn":  "Play It Safe- Manage Security Risks",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-013",
        "sort":  13,
        "image":  "./items/item-013.png",
        "originalFile":  "【Google】Sound the Alarm Detection and Response.png",
        "titleZh":  "Sound the Alarm Detection and Response",
        "titleEn":  "Sound the Alarm Detection and Response",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-014",
        "sort":  14,
        "image":  "./items/item-014.png",
        "originalFile":  "【Google】Tools of the Trade Linux and SQL.png",
        "titleZh":  "Tools of the Trade Linux and SQL",
        "titleEn":  "Tools of the Trade Linux and SQL",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-015",
        "sort":  15,
        "image":  "./items/item-015.png",
        "originalFile":  "【Google】育廷 施 _ Google Cloud Skills Boost_1.png",
        "titleZh":  "育廷 施 _ Google Cloud Skills Boost",
        "titleEn":  "育廷 施 _ Google Cloud Skills Boost",
        "categoryKey":  "google",
        "issuerZh":  "Google / Google Cloud",
        "issuerEn":  "Google / Google Cloud",
        "year":  ""
    },
    {
        "id":  "cert-016",
        "sort":  16,
        "image":  "./items/item-016.png",
        "originalFile":  "【研習證明】(1131113)_國立臺中教育大學施育廷_1.png",
        "titleZh":  "(1131113)_國立臺中教育大學施育廷",
        "titleEn":  "Training Certificate: (1131113)_國立臺中教育大學施育廷",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-017",
        "sort":  17,
        "image":  "./items/item-017.png",
        "originalFile":  "【研習證明】(1131122)_國立臺中教育大學施育廷_1.png",
        "titleZh":  "(1131122)_國立臺中教育大學施育廷",
        "titleEn":  "Training Certificate: (1131122)_國立臺中教育大學施育廷",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-018",
        "sort":  18,
        "image":  "./items/item-018.jpg",
        "originalFile":  "【研習證明】2025 TaiwanCALL 研討會感謝函.jpg",
        "titleZh":  "2025 TaiwanCALL 研討會感謝函",
        "titleEn":  "Training Certificate: 2025 TaiwanCALL 研討會感謝函",
        "categoryKey":  "training",
        "issuerZh":  "TaiwanCALL",
        "issuerEn":  "TaiwanCALL",
        "year":  "2025"
    },
    {
        "id":  "cert-019",
        "sort":  19,
        "image":  "./items/item-019.png",
        "originalFile":  "【研習證明】2025 TaiwanCALL_Certificate .png",
        "titleZh":  "2025 TaiwanCALL_Certificate",
        "titleEn":  "Training Certificate: 2025 TaiwanCALL_Certificate",
        "categoryKey":  "training",
        "issuerZh":  "TaiwanCALL",
        "issuerEn":  "TaiwanCALL",
        "year":  "2025"
    },
    {
        "id":  "cert-020",
        "sort":  20,
        "image":  "./items/item-020.jpg",
        "originalFile":  "【研習證明】AI Azure 研習課程.jpg",
        "titleZh":  "AI Azure 研習課程",
        "titleEn":  "Training Certificate: AI Azure 研習課程",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-021",
        "sort":  21,
        "image":  "./items/item-021.jpg",
        "originalFile":  "【研習證明】AI Azure 研習課程時數.jpg",
        "titleZh":  "AI Azure 研習課程時數",
        "titleEn":  "Training Certificate: AI Azure 研習課程時數",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-022",
        "sort":  22,
        "image":  "./items/item-022.jpg",
        "originalFile":  "【研習證明】AI4Good施育廷.jpg",
        "titleZh":  "AI4Good施育廷",
        "titleEn":  "Training Certificate: AI4Good施育廷",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-023",
        "sort":  23,
        "image":  "./items/item-023.jpg",
        "originalFile":  "【研習證明】CAIIAS 2025 國際學術研討會：AI發展、教育創新與文化永續.jpg",
        "titleZh":  "CAIIAS 2025 國際學術研討會：AI發展、教育創新與文化永續",
        "titleEn":  "Training Certificate: CAIIAS 2025 國際學術研討會：AI發展、教育創新與文化永續",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2025"
    },
    {
        "id":  "cert-024",
        "sort":  24,
        "image":  "./items/item-024.png",
        "originalFile":  "【研習證明】Copilot X Design Thinking_結訓證書_(iABC-DnE)_20240828-29 施育廷.png",
        "titleZh":  "Copilot X Design Thinking_結訓證書_(iABC-DnE)_20240828-29 施育廷",
        "titleEn":  "Training Certificate: Copilot X Design Thinking_結訓證書_(iABC-DnE)_20240828-29 施育廷",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2024"
    },
    {
        "id":  "cert-025",
        "sort":  25,
        "image":  "./items/item-025.png",
        "originalFile":  "【研習證明】人工智慧浪潮下之資訊科學與數位學習之變革與挑戰論壇_1.png",
        "titleZh":  "人工智慧浪潮下之資訊科學與數位學習之變革與挑戰論壇",
        "titleEn":  "Training Certificate: 人工智慧浪潮下之資訊科學與數位學習之變革與挑戰論壇",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-026",
        "sort":  26,
        "image":  "./items/item-026.png",
        "originalFile":  "【研習證明】生成式AI融入教學_1.png",
        "titleZh":  "生成式AI融入教學",
        "titleEn":  "Training Certificate: 生成式AI融入教學",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-027",
        "sort":  27,
        "image":  "./items/item-027.png",
        "originalFile":  "【研習證明】生成式AI融入教學「想像__AI協作的教學_以「科技與社會」課程為例」共_1.png",
        "titleZh":  "生成式AI融入教學「想像__AI協作的教學_以「科技與社會」課程為例」共",
        "titleEn":  "Training Certificate: 生成式AI融入教學「想像__AI協作的教學_以「科技與社會」課程為例」共",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-028",
        "sort":  28,
        "image":  "./items/item-028.png",
        "originalFile":  "【研習證明】如何正確使用AI工具學習英語_1.png",
        "titleZh":  "如何正確使用AI工具學習英語",
        "titleEn":  "Training Certificate: 如何正確使用AI工具學習英語",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-029",
        "sort":  29,
        "image":  "./items/item-029.png",
        "originalFile":  "【研習證明】資料科學深度學習.png",
        "titleZh":  "資料科學深度學習",
        "titleEn":  "Training Certificate: 資料科學深度學習",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-030",
        "sort":  30,
        "image":  "./items/item-030.jpg",
        "originalFile":  "【研習證明】跨文化智慧 × 創新互動EMI 教學發展社群-視覺敘事的 GAI 創意加速器：中階手機行銷專案 講座.jpg",
        "titleZh":  "跨文化智慧 × 創新互動EMI 教學發展社群-視覺敘事的 GAI 創意加速器：中階手機行銷專案 講座",
        "titleEn":  "Training Certificate: 跨文化智慧 × 創新互動EMI 教學發展社群-視覺敘事的 GAI 創意加速器：中階手機行銷專案 講座",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-031",
        "sort":  31,
        "image":  "./items/item-031.jpg",
        "originalFile":  "【研習證明】應教學門研習證書1100611.jpg",
        "titleZh":  "應教學門研習證書1100611",
        "titleEn":  "Training Certificate: 應教學門研習證書1100611",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-032",
        "sort":  32,
        "image":  "./items/item-032.jpg",
        "originalFile":  "【研習證明】應教學門研習證書1100702.jpg",
        "titleZh":  "應教學門研習證書1100702",
        "titleEn":  "Training Certificate: 應教學門研習證書1100702",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-033",
        "sort":  33,
        "image":  "./items/item-033.jpg",
        "originalFile":  "【研習證明】應教學門研習證書1100716.jpg",
        "titleZh":  "應教學門研習證書1100716",
        "titleEn":  "Training Certificate: 應教學門研習證書1100716",
        "categoryKey":  "training",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-034",
        "sort":  34,
        "image":  "./items/item-034.jpg",
        "originalFile":  "【專利證書】I918530.PDF.jpg",
        "titleZh":  "I918530",
        "titleEn":  "Patent Record: I918530",
        "categoryKey":  "patent",
        "issuerZh":  "Intellectual Property Authority",
        "issuerEn":  "Intellectual Property Authority",
        "year":  ""
    },
    {
        "id":  "cert-035",
        "sort":  35,
        "image":  "./items/item-035.jpg",
        "originalFile":  "【發表】2018_TWELF.jpg",
        "titleZh":  "2018_TWELF",
        "titleEn":  "Presentation Record: 2018_TWELF",
        "categoryKey":  "presentation",
        "issuerZh":  "TWELF",
        "issuerEn":  "TWELF",
        "year":  "2018"
    },
    {
        "id":  "cert-036",
        "sort":  36,
        "image":  "./items/item-036.png",
        "originalFile":  "【發表】2019_ICEA.png",
        "titleZh":  "2019_ICEA",
        "titleEn":  "Presentation Record: 2019_ICEA",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2019"
    },
    {
        "id":  "cert-037",
        "sort":  37,
        "image":  "./items/item-037.png",
        "originalFile":  "【發表】2022_ETS.png",
        "titleZh":  "2022_ETS",
        "titleEn":  "Presentation Record: 2022_ETS",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2022"
    },
    {
        "id":  "cert-038",
        "sort":  38,
        "image":  "./items/item-038.png",
        "originalFile":  "【發表】2022_ICITL.png",
        "titleZh":  "2022_ICITL",
        "titleEn":  "Presentation Record: 2022_ICITL",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2022"
    },
    {
        "id":  "cert-039",
        "sort":  39,
        "image":  "./items/item-039.jpg",
        "originalFile":  "【發表】2022_TAECT-1.jpg",
        "titleZh":  "2022_TAECT-1",
        "titleEn":  "Presentation Record: 2022_TAECT-1",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2022"
    },
    {
        "id":  "cert-040",
        "sort":  40,
        "image":  "./items/item-040.jpg",
        "originalFile":  "【發表】2022_TAECT-2.jpg",
        "titleZh":  "2022_TAECT-2",
        "titleEn":  "Presentation Record: 2022_TAECT-2",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2022"
    },
    {
        "id":  "cert-041",
        "sort":  41,
        "image":  "./items/item-041.jpg",
        "originalFile":  "【發表】2023 CRDTE_.jpg",
        "titleZh":  "2023 CRDTE_",
        "titleEn":  "Presentation Record: 2023 CRDTE_",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2023"
    },
    {
        "id":  "cert-042",
        "sort":  42,
        "image":  "./items/item-042.jpg",
        "originalFile":  "【發表】2023_BEMST.jpg",
        "titleZh":  "2023_BEMST",
        "titleEn":  "Presentation Record: 2023_BEMST",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2023"
    },
    {
        "id":  "cert-043",
        "sort":  43,
        "image":  "./items/item-043.jpg",
        "originalFile":  "【發表】2024_BEMST.jpg",
        "titleZh":  "2024_BEMST",
        "titleEn":  "Presentation Record: 2024_BEMST",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2024"
    },
    {
        "id":  "cert-044",
        "sort":  44,
        "image":  "./items/item-044.jpg",
        "originalFile":  "【發表】2025 APERA-TERA.jpg",
        "titleZh":  "2025 APERA-TERA",
        "titleEn":  "Presentation Record: 2025 APERA-TERA",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2025"
    },
    {
        "id":  "cert-045",
        "sort":  45,
        "image":  "./items/item-045.jpg",
        "originalFile":  "【發表】2025 BEMST.jpg",
        "titleZh":  "2025 BEMST",
        "titleEn":  "Presentation Record: 2025 BEMST",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2025"
    },
    {
        "id":  "cert-046",
        "sort":  46,
        "image":  "./items/item-046.jpg",
        "originalFile":  "【發表】2025 TANET NCS.jpg",
        "titleZh":  "2025 TANET NCS",
        "titleEn":  "Presentation Record: 2025 TANET NCS",
        "categoryKey":  "presentation",
        "issuerZh":  "TANET",
        "issuerEn":  "TANET",
        "year":  "2025"
    },
    {
        "id":  "cert-047",
        "sort":  47,
        "image":  "./items/item-047.jpg",
        "originalFile":  "【發表】2025自主學習節_2.jpg",
        "titleZh":  "2025自主學習節_2",
        "titleEn":  "Presentation Record: 2025自主學習節_2",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2025"
    },
    {
        "id":  "cert-048",
        "sort":  48,
        "image":  "./items/item-048.jpg",
        "originalFile":  "【發表】2025自主學習節_參加證明.jpg",
        "titleZh":  "2025自主學習節_參加證明",
        "titleEn":  "Presentation Record: 2025自主學習節_參加證明",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2025"
    },
    {
        "id":  "cert-049",
        "sort":  49,
        "image":  "./items/item-049.jpg",
        "originalFile":  "【發表】2025自主學習節1.jpg",
        "titleZh":  "2025自主學習節1",
        "titleEn":  "Presentation Record: 2025自主學習節1",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2025"
    },
    {
        "id":  "cert-050",
        "sort":  50,
        "image":  "./items/item-050.jpg",
        "originalFile":  "【發表】2025自主學習節優秀論文獎.jpg",
        "titleZh":  "2025自主學習節優秀論文獎",
        "titleEn":  "Presentation Record: 2025自主學習節優秀論文獎",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2025"
    },
    {
        "id":  "cert-051",
        "sort":  51,
        "image":  "./items/item-051.jpg",
        "originalFile":  "【發表】2026_ETS.jpg",
        "titleZh":  "2026_ETS",
        "titleEn":  "Presentation Record: 2026_ETS",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2026"
    },
    {
        "id":  "cert-052",
        "sort":  52,
        "image":  "./items/item-052.jpg",
        "originalFile":  "【發表】2026_ETS佳作論文獎.jpg",
        "titleZh":  "2026_ETS佳作論文獎",
        "titleEn":  "Presentation Record: 2026_ETS佳作論文獎",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2026"
    },
    {
        "id":  "cert-053",
        "sort":  53,
        "image":  "./items/item-053.jpg",
        "originalFile":  "【發表】2026_TWELF.jpg",
        "titleZh":  "2026_TWELF",
        "titleEn":  "Presentation Record: 2026_TWELF",
        "categoryKey":  "presentation",
        "issuerZh":  "TWELF",
        "issuerEn":  "TWELF",
        "year":  "2026"
    },
    {
        "id":  "cert-054",
        "sort":  54,
        "image":  "./items/item-054.jpg",
        "originalFile":  "【發表】AEIT_2025.jpg",
        "titleZh":  "AEIT_2025",
        "titleEn":  "Presentation Record: AEIT_2025",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "2025"
    },
    {
        "id":  "cert-055",
        "sort":  55,
        "image":  "./items/item-055.jpg",
        "originalFile":  "【發表】Education Sciences.jpg",
        "titleZh":  "Education Sciences",
        "titleEn":  "Presentation Record: Education Sciences",
        "categoryKey":  "presentation",
        "issuerZh":  "Education Sciences",
        "issuerEn":  "Education Sciences",
        "year":  ""
    },
    {
        "id":  "cert-056",
        "sort":  56,
        "image":  "./items/item-056.png",
        "originalFile":  "【發表】ICEET2025.png",
        "titleZh":  "ICEET2025",
        "titleEn":  "Presentation Record: ICEET2025",
        "categoryKey":  "presentation",
        "issuerZh":  "ICEET",
        "issuerEn":  "ICEET",
        "year":  "2025"
    },
    {
        "id":  "cert-057",
        "sort":  57,
        "image":  "./items/item-057.jpg",
        "originalFile":  "【發表】ICEET2026論文優選獎A.jpg",
        "titleZh":  "ICEET2026論文優選獎A",
        "titleEn":  "Presentation Record: ICEET2026論文優選獎A",
        "categoryKey":  "presentation",
        "issuerZh":  "ICEET",
        "issuerEn":  "ICEET",
        "year":  "2026"
    },
    {
        "id":  "cert-058",
        "sort":  58,
        "image":  "./items/item-058.jpg",
        "originalFile":  "【發表】ICEET2026論文優選獎B.jpg",
        "titleZh":  "ICEET2026論文優選獎B",
        "titleEn":  "Presentation Record: ICEET2026論文優選獎B",
        "categoryKey":  "presentation",
        "issuerZh":  "ICEET",
        "issuerEn":  "ICEET",
        "year":  "2026"
    },
    {
        "id":  "cert-059",
        "sort":  59,
        "image":  "./items/item-059.png",
        "originalFile":  "【發表】ICEET-O01.png",
        "titleZh":  "ICEET-O01",
        "titleEn":  "Presentation Record: ICEET-O01",
        "categoryKey":  "presentation",
        "issuerZh":  "ICEET",
        "issuerEn":  "ICEET",
        "year":  ""
    },
    {
        "id":  "cert-060",
        "sort":  60,
        "image":  "./items/item-060.png",
        "originalFile":  "【發表】ICEET--O04.png",
        "titleZh":  "ICEET--O04",
        "titleEn":  "Presentation Record: ICEET--O04",
        "categoryKey":  "presentation",
        "issuerZh":  "ICEET",
        "issuerEn":  "ICEET",
        "year":  ""
    },
    {
        "id":  "cert-061",
        "sort":  61,
        "image":  "./items/item-061.jpg",
        "originalFile":  "【發表】ICEET最佳論文獎.jpg",
        "titleZh":  "ICEET最佳論文獎",
        "titleEn":  "Presentation Record: ICEET最佳論文獎",
        "categoryKey":  "presentation",
        "issuerZh":  "ICEET",
        "issuerEn":  "ICEET",
        "year":  ""
    },
    {
        "id":  "cert-062",
        "sort":  62,
        "image":  "./items/item-062.jpg",
        "originalFile":  "【發表】ICEET論文優選獎.jpg",
        "titleZh":  "ICEET論文優選獎",
        "titleEn":  "Presentation Record: ICEET論文優選獎",
        "categoryKey":  "presentation",
        "issuerZh":  "ICEET",
        "issuerEn":  "ICEET",
        "year":  ""
    },
    {
        "id":  "cert-063",
        "sort":  63,
        "image":  "./items/item-063.jpg",
        "originalFile":  "【發表】測驗學會.jpg",
        "titleZh":  "測驗學會",
        "titleEn":  "Presentation Record: 測驗學會",
        "categoryKey":  "presentation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-064",
        "sort":  64,
        "image":  "./items/item-064.jpg",
        "originalFile":  "【感謝狀】111高教深耕感謝狀.jpg",
        "titleZh":  "111高教深耕感謝狀",
        "titleEn":  "Letter of Appreciation: 111高教深耕感謝狀",
        "categoryKey":  "appreciation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  "111"
    },
    {
        "id":  "cert-065",
        "sort":  65,
        "image":  "./items/item-065.jpg",
        "originalFile":  "【感謝狀】AI工具應用,關於醫療與放射科輔助工作,Gemini 雲端整合與提示詞工程 (1).jpg",
        "titleZh":  "AI工具應用,關於醫療與放射科輔助工作,Gemini 雲端整合與提示詞工程 (1)",
        "titleEn":  "Letter of Appreciation: AI工具應用,關於醫療與放射科輔助工作,Gemini 雲端整合與提示詞工程 (1)",
        "categoryKey":  "appreciation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-066",
        "sort":  66,
        "image":  "./items/item-066.jpg",
        "originalFile":  "【感謝狀】運用AI輔助學習講座講師.jpg",
        "titleZh":  "運用AI輔助學習講座講師",
        "titleEn":  "Letter of Appreciation: 運用AI輔助學習講座講師",
        "categoryKey":  "appreciation",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-067",
        "sort":  67,
        "image":  "./items/item-067.jpg",
        "originalFile":  "【聘書】NTCU_110-2.jpg",
        "titleZh":  "NTCU_110-2",
        "titleEn":  "Appointment Letter: NTCU_110-2",
        "categoryKey":  "appointment",
        "issuerZh":  "National Taichung University of Education",
        "issuerEn":  "National Taichung University of Education",
        "year":  ""
    },
    {
        "id":  "cert-068",
        "sort":  68,
        "image":  "./items/item-068.jpg",
        "originalFile":  "【聘書】NTCU_111-1.jpg",
        "titleZh":  "NTCU_111-1",
        "titleEn":  "Appointment Letter: NTCU_111-1",
        "categoryKey":  "appointment",
        "issuerZh":  "National Taichung University of Education",
        "issuerEn":  "National Taichung University of Education",
        "year":  ""
    },
    {
        "id":  "cert-069",
        "sort":  69,
        "image":  "./items/item-069.jpg",
        "originalFile":  "【聘書】NTCU_111-2.jpg",
        "titleZh":  "NTCU_111-2",
        "titleEn":  "Appointment Letter: NTCU_111-2",
        "categoryKey":  "appointment",
        "issuerZh":  "National Taichung University of Education",
        "issuerEn":  "National Taichung University of Education",
        "year":  ""
    },
    {
        "id":  "cert-070",
        "sort":  70,
        "image":  "./items/item-070.jpg",
        "originalFile":  "【聘書】NTCU_112.jpg",
        "titleZh":  "NTCU_112",
        "titleEn":  "Appointment Letter: NTCU_112",
        "categoryKey":  "appointment",
        "issuerZh":  "National Taichung University of Education",
        "issuerEn":  "National Taichung University of Education",
        "year":  ""
    },
    {
        "id":  "cert-071",
        "sort":  71,
        "image":  "./items/item-071.jpg",
        "originalFile":  "【聘書】NTCU_113-1.jpg",
        "titleZh":  "NTCU_113-1",
        "titleEn":  "Appointment Letter: NTCU_113-1",
        "categoryKey":  "appointment",
        "issuerZh":  "National Taichung University of Education",
        "issuerEn":  "National Taichung University of Education",
        "year":  ""
    },
    {
        "id":  "cert-072",
        "sort":  72,
        "image":  "./items/item-072.jpg",
        "originalFile":  "【聘書】NTCU_113-2.jpg",
        "titleZh":  "NTCU_113-2",
        "titleEn":  "Appointment Letter: NTCU_113-2",
        "categoryKey":  "appointment",
        "issuerZh":  "National Taichung University of Education",
        "issuerEn":  "National Taichung University of Education",
        "year":  ""
    },
    {
        "id":  "cert-073",
        "sort":  73,
        "image":  "./items/item-073.jpg",
        "originalFile":  "【聘書】NTCU_114-1.jpg",
        "titleZh":  "NTCU_114-1",
        "titleEn":  "Appointment Letter: NTCU_114-1",
        "categoryKey":  "appointment",
        "issuerZh":  "National Taichung University of Education",
        "issuerEn":  "National Taichung University of Education",
        "year":  ""
    },
    {
        "id":  "cert-074",
        "sort":  74,
        "image":  "./items/item-074.jpg",
        "originalFile":  "【聘書】NTCU_114-2.jpg",
        "titleZh":  "NTCU_114-2",
        "titleEn":  "Appointment Letter: NTCU_114-2",
        "categoryKey":  "appointment",
        "issuerZh":  "National Taichung University of Education",
        "issuerEn":  "National Taichung University of Education",
        "year":  ""
    },
    {
        "id":  "cert-075",
        "sort":  75,
        "image":  "./items/item-075.jpg",
        "originalFile":  "【證明】博士候選人證明書.jpg",
        "titleZh":  "博士候選人證明書",
        "titleEn":  "Academic Proof: 博士候選人證明書",
        "categoryKey":  "status",
        "issuerZh":  "Academic Documentation",
        "issuerEn":  "Academic Documentation",
        "year":  ""
    },
    {
        "id":  "cert-076",
        "sort":  76,
        "image":  "./items/item-076.jpg",
        "originalFile":  "【證照】(MTA)Microsoft Technology Associate：Database Administration Fundamentals1.jpg",
        "titleZh":  "(MTA)Microsoft Technology Associate：Database Administration Fundamentals1",
        "titleEn":  "Certification: (MTA)Microsoft Technology Associate：Database Administration Fundamentals1",
        "categoryKey":  "license",
        "issuerZh":  "Microsoft",
        "issuerEn":  "Microsoft",
        "year":  ""
    },
    {
        "id":  "cert-077",
        "sort":  77,
        "image":  "./items/item-077.jpg",
        "originalFile":  "【證照】(MTA)Microsoft Technology Associate：Database Administration Fundamentals2.jpg",
        "titleZh":  "(MTA)Microsoft Technology Associate：Database Administration Fundamentals2",
        "titleEn":  "Certification: (MTA)Microsoft Technology Associate：Database Administration Fundamentals2",
        "categoryKey":  "license",
        "issuerZh":  "Microsoft",
        "issuerEn":  "Microsoft",
        "year":  ""
    },
    {
        "id":  "cert-078",
        "sort":  78,
        "image":  "./items/item-078.jpg",
        "originalFile":  "【證照】Foundation Certificate in EPC Architecture Framework.jpg",
        "titleZh":  "Foundation Certificate in EPC Architecture Framework",
        "titleEn":  "Certification: Foundation Certificate in EPC Architecture Framework",
        "categoryKey":  "license",
        "issuerZh":  "Relevant issuing or hosting body",
        "issuerEn":  "Relevant issuing or hosting body",
        "year":  ""
    },
    {
        "id":  "cert-079",
        "sort":  79,
        "image":  "./items/item-079.png",
        "originalFile":  "【證照】Google 認證教育工作者第 1 級.png",
        "titleZh":  "Google 認證教育工作者第 1 級",
        "titleEn":  "Certification: Google 認證教育工作者第 1 級",
        "categoryKey":  "license",
        "issuerZh":  "Google",
        "issuerEn":  "Google",
        "year":  ""
    },
    {
        "id":  "cert-080",
        "sort":  80,
        "image":  "./items/item-080.png",
        "originalFile":  "【證照】Google 認證教育工作者第 2 級.png",
        "titleZh":  "Google 認證教育工作者第 2 級",
        "titleEn":  "Certification: Google 認證教育工作者第 2 級",
        "categoryKey":  "license",
        "issuerZh":  "Google",
        "issuerEn":  "Google",
        "year":  ""
    },
    {
        "id":  "cert-081",
        "sort":  81,
        "image":  "./items/item-081.jpg",
        "originalFile":  "【證照】Oracle Certified Java Programmer (OCJP).jpg",
        "titleZh":  "Oracle Certified Java Programmer (OCJP)",
        "titleEn":  "Certification: Oracle Certified Java Programmer (OCJP)",
        "categoryKey":  "license",
        "issuerZh":  "Oracle",
        "issuerEn":  "Oracle",
        "year":  ""
    }
];